import type { Efficacy, Health, Meta, Metrics, Policies, Routing, Spend, Summary, TaskDetail, TaskList } from '../api-types'

export const meta: Meta = { metric_definition_version: 'phase5-v1', start: '2026-08-01T00:00:00Z', end: '2026-09-01T00:00:00Z', generated_at: '2026-09-01T12:00:00Z', freshness: '2026-09-01T11:58:00Z', synthetic: true, currency: 'USD', filters: { application: null }, notes: [] }
export const known = (amount = '1.2500') => ({ amount, known_subtotal: amount, missing_count: 0, status: 'known' as const })
export const partial = { amount: null, known_subtotal: '0.2500', missing_count: 1, status: 'partial' as const }
export const rate = (value = .8, numerator = 8, denominator = 10) => ({ value, numerator, denominator })
export const metrics: Metrics = { total_tasks: 10, terminal_tasks: 9, pending_tasks: 1, cancelled_tasks: 0, blocked_tasks: 0, successful_tasks: 8, first_pass_success: rate(.7, 7, 10), final_success: rate(), escalation_rate: rate(.2, 2, 10), infrastructure_retry_rate: rate(.1, 1, 10), tool_recovery_rate: rate(0, 0, 10), cost: known('1.25'), cost_per_task: known('.125'), effective_cost_per_success: partial, p50_latency_ms: 800, p95_latency_ms: 2100 }
export const summary: Summary = { meta, metrics, spend_today: known('.12'), spend_mtd: known('1.25'), projected_month: known('2.5'), forecast_method: 'linear_mtd_run_rate', policy_versions: ['policy-v1'] }
export const spend: Spend = { meta, production: known('1.25'), shadow: known('.20'), all_spend: known('1.45'), unallocated: { amount: null, known_subtotal: '0', missing_count: 0, status: 'unavailable' }, series: [{ date: '2026-08-01', production: known('.5'), shadow: known('.1'), cumulative_production: known('.5') }, { date: '2026-08-02', production: partial, shadow: known('.1'), cumulative_production: partial }], by_model: [{ key: 'gpt-5.6-terra', cost: known('.75'), count: 6 }], by_effort: [{ key: 'medium', cost: known('.75'), count: 6 }], by_application: [{ key: 'support', cost: known('1.25'), count: 10 }], by_task_family: [{ key: 'engineering', cost: known('1.25'), count: 10 }], by_policy: [{ key: 'policy-v1', cost: known('1.25'), count: 10 }], by_purpose: [{ key: 'generation', cost: known('1'), count: 10 }], by_contribution: [{ key: 'generation', cost: known('1'), count: 10 }, { key: 'validation', cost: known('.25'), count: 8 }] }
export const routing: Routing = { meta, models: [{ key: 'gpt-5.6-terra', count: 10, share: 1 }], efforts: [{ key: 'medium', count: 10, share: 1 }], complexities: [{ key: '3', count: 10, share: 1 }], task_families: [{ key: 'engineering', count: 10, share: 1 }], validations: [{ key: 'independent', count: 8, share: .8 }], rationale_codes: [{ key: 'capability_fit', count: 10, share: 1 }], family_model_flow: [{ source: 'engineering', target: 'gpt-5.6-terra', count: 10 }], escalation_flow: [{ source: 'gpt-5.6-luna', target: 'gpt-5.6-terra', count: 2 }], preferred_floor_relaxation: rate(.1, 1, 10), constrained_fallback: rate(0, 0, 10), trend: [{ date: '2026-08-01', first_pass_success: rate(.7, 7, 10), final_success: rate(), effective_cost_per_success: partial }] }
export const efficacy: Efficacy = { meta, cohorts: [{ key: 'gpt-5.6-terra/medium', model: 'gpt-5.6-terra', effort: 'medium', policy_version: null, metrics, quality: { comparable: true, reason: null, groups: [{ rubric_version: 'rubric-v2', check: 'correctness', score_min: 0, score_max: 1, mean: .88, sample_size: 8, role: 'primary' }] }, insufficient_sample: true }] }
export const policies: Policies = { meta, cohorts: [{ ...efficacy.cohorts[0], key: 'policy-v1', model: null, effort: null, policy_version: 'policy-v1' }], comparison_note: 'Cohorts under 30 terminal tasks are insufficient.' }
export const health: Health = { meta, state: 'STALE', production_ready: false, readiness_note: 'Production readiness is unknown from retained local evidence.', components: [{ component: 'database', model: null, capability: null, state: 'HEALTHY', observed_at: '2026-09-01T11:50:00Z', valid_until: '2026-09-01T12:10:00Z', circuit_state: 'closed', failure_count: 0, latency_ms: 2, required: true }, { component: 'model', model: 'gpt-5.6-terra', capability: 'generation', state: 'STALE', observed_at: '2026-08-01T00:00:00Z', valid_until: '2026-08-01T00:10:00Z', circuit_state: 'unknown', failure_count: 1, latency_ms: null, required: true }], outbox_pending: 2, oldest_pending_at: '2026-09-01T11:00:00Z', p50_latency_ms: 800, p95_latency_ms: 2100, failure_rate: rate(.1, 1, 10), timeouts: 1, rate_limits: 0, degraded_periods: [{ start: '2026-08-05T12:00:00Z', end: '2026-08-05T13:00:00Z', component: 'model', state: 'DEGRADED' }] }
export const task = { task_id: 'task-safe-1', created_at: '2026-08-20T12:00:00Z', application: 'support', task_family: 'engineering', complexity: 3, model: 'gpt-5.6-terra', effort: 'medium', status: 'succeeded', cost: partial, latency_ms: 2100, escalated: true, policy_version: 'policy-v1', synthetic: true }
export const tasks: TaskList = { meta, items: [task], total: 1, offset: 0, limit: 25 }
export const taskDetail: TaskDetail = { meta, task, timeline: [{ id: 'step-1', kind: 'created', timestamp: task.created_at, title: 'Created', model: null, effort: null, rationale_codes: [], tokens: {}, cost: null, latency_ms: null, validation: null, failure_type: null, recovery_action: null, health_snapshot_id: null, policy_version: 'policy-v1', pricing_version: null, role: 'primary', metadata: { source: 'local' } }, { id: 'step-2', kind: 'attempt', timestamp: '2026-08-20T12:00:01Z', title: 'Attempt 1', model: 'gpt-5.6-terra', effort: 'medium', rationale_codes: ['capability_fit'], tokens: { input_tokens: 120, output_tokens: 80 }, cost: partial, latency_ms: 1800, validation: null, failure_type: null, recovery_action: null, health_snapshot_id: 'health-safe-1', policy_version: 'policy-v1', pricing_version: 'pricing-v1', role: 'shadow', metadata: { purpose: 'generation' } }], total: 2, offset: 0, limit: 100 }

export function responseFor(url: string): unknown {
  if (url.includes('/telemetry/summary')) return summary
  if (url.includes('/telemetry/spend')) return spend
  if (url.includes('/telemetry/routing')) return routing
  if (url.includes('/telemetry/efficacy')) return efficacy
  if (url.includes('/telemetry/health')) return health
  if (url.includes('/telemetry/models')) return efficacy
  if (url.includes('/telemetry/task-families')) return { ...efficacy, cohorts: [{ ...efficacy.cohorts[0], key: 'engineering' }] }
  if (url.includes('/telemetry/policies')) return policies
  if (url.includes('/v1/tasks/task-safe-1')) return taskDetail
  if (url.includes('/v1/tasks')) return tasks
  throw new Error(`Unhandled fixture URL: ${url}`)
}
