"""Dependency direction and process-level offline guarantees."""

import ast
import os
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
FORBIDDEN = {"fastapi", "sqlalchemy", "openai", "dashboard", "frontend", "evals",
             "requests", "httpx", "aiohttp"}


def test_runtime_source_has_no_forbidden_boundary_imports():
    for path in (ROOT / "src/model_router").rglob("*.py"):
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            imports = []
            if isinstance(node, ast.Import):
                imports = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                imports = [node.module or ""]
            # Phase 2 adds exactly one external adapter. The pure routing core,
            # policy and classifier still have the original import restriction.
            allowed = {"openai"} if path == ROOT / "src/model_router/execution/openai_provider.py" else set()
            # Phase 3 adapters own their frameworks; core and orchestration do not.
            if path.is_relative_to(ROOT / "src/model_router/storage"):
                allowed |= {"sqlalchemy", "alembic"}
            if path.is_relative_to(ROOT / "src/model_router/service"):
                allowed |= {"fastapi"}
            assert not any(name.split(".")[0] in FORBIDDEN - allowed for name in imports), path


def test_core_and_policy_never_depend_on_selector():
    for directory in ("core", "policy"):
        for path in (ROOT / "src/model_router" / directory).rglob("*.py"):
            tree = ast.parse(path.read_text())
            for node in ast.walk(tree):
                if isinstance(node, ast.ImportFrom):
                    assert node.module != "model_router.router", path


def test_import_and_routing_work_with_forbidden_imports_and_network_disabled():
    program = '''
import importlib.abc
import sys
import socket
class BoundaryGuard(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname.split('.')[0] in {'fastapi','sqlalchemy','openai','dashboard','frontend','evals'}:
            raise AssertionError('forbidden import: ' + fullname)
sys.meta_path.insert(0, BoundaryGuard())
def no_network(*args, **kwargs):
    raise AssertionError('network access attempted')
socket.socket.connect = no_network
socket.create_connection = no_network
from model_router.router import route
from model_router.policy.loader import load_bundle
from model_router.core.contracts import Request, Classification, EnvironmentSnapshot
bundle = load_bundle('config')
request = Request(task_id='offline', trace_id='trace', consequence='low',
                  requirements=['text_input', 'text_output'],
                  context={'input_tokens': 100, 'expected_output_tokens': 10})
classification = Classification(task_family='extract', confidence=1.0, provenance='offline-v1',
    components={name: 0 for name in bundle.policy['complexity']['components']})
environment = EnvironmentSnapshot(snapshot_id='offline', clock='2026-09-06T20:00:00Z',
                                  pricing_version='offline-quotes-v1')
decision = route(request, classification, environment, bundle)
assert decision.routing_result == 'valid'
assert not decision.executable
assert decision == route(request, classification, environment, bundle)
'''
    environment = os.environ.copy()
    environment.pop("OPENAI_API_KEY", None)
    # Match pytest's explicit source checkout path in the fresh process too.
    environment["PYTHONPATH"] = str(ROOT / "src")
    result = subprocess.run([sys.executable, "-c", program], cwd=ROOT, env=environment,
                            text=True, capture_output=True)
    assert result.returncode == 0, result.stderr


def test_approved_oracle_and_config_files_are_byte_identical():
    # Baseline commit is an independent source, not a snapshot generated by the
    # implementation. New runner/adapter files are deliberately outside this set.
    paths = [ROOT / "config" / name for name in ("models.yaml", "routing-policy.yaml", "budgets.yaml", "validation.yaml")]
    paths.extend(path for folder in ("cases", "fixtures", "schema")
                 for path in (ROOT / "evals" / folder).rglob("*") if path.is_file())
    paths.extend(ROOT / "evals" / name for name in ("grader.py", "schema.py", "run_local.py"))
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        original = subprocess.run(["git", "show", f"f42ecc9615de547528de7cbc00a2624649140f57:{rel}"],
                                  cwd=ROOT, capture_output=True, check=True).stdout
        assert path.read_bytes() == original, rel
